### ISSUE TITLE
Scope not closed?

### ISSUE THREAD

**Issue by gerloh** [AxonFramework/extension-tracing#24]
I don't see the first created parent scope being closed. According to the opentracing documentation : 
"It is a programming error to neglect to call {@link Scope#close()} on the returned instance "
Probably the scope is closed when the thread ends, but that could lead to strange behaviour when using a threadpool. 
Indeed i sometimes see (too long) lived traces, when used with other tracing instrumentated modules like "opentracing-spring-jaeger-web-starter" itself. 
Of course this is only an issue if axon is creating the scope, which, mostly, is not the case, as there is almost always a rest endpoind or some other starting point, but i think it should not be a default assumption.

**Comment by smcvb** [comment]
I have a hunch this ties in to issue #16 and pull request #17 provided by @jvanderkallen.

Would you mind checking whether my assumption is correct here @gerloh? 
If so, the problem would be resolved as soon as 4.3 of the Tracing extension is released.

**Comment by gerloh** [comment]
Well actually i already did check that PR and also #20 , but i don't see a scope being closed. The span is created with `spanBuilder.startActive(false))` , that means  the scope is also not closed by finishing the span. 
It is a normal procedure to use "try with resources"  to create a span and scope, so it is closed at the end of the try or close it it manually in the finally block.
Maybe i overlook something and maybe @jvanderkallen kan elaborate on this ?

**Comment by gerloh** [comment]
@ghilainm , what do you think of this ? 
Also i noticed that a span can be closed in another thread than it is started. This can be an issue if you want you use MDC like in this Observer : 
https://github.com/dschulten/karaf/blob/opentracing-mdc/examples/karaf-camel-example/karaf-camel-example-java/src/main/java/org/apache/karaf/examples/camel/java/MdcTracerObserver.java

**Comment by abuijze** [comment]
There seems to be a wrong instance of  `activateSpan(parentSpan)`, following a `try (Scope ignored = tracer.activateSpan(childSpan)) { ... }`. Since the childSpan is only executed on in a Scope, there is no need to (re)activate the parent span. That is automatically done when the scope of the childSpan ended. In fact, the (re)activation of the parent span this way may cause an additional Scope to be added to the stack, which isn't properly cleared anymore.

The culprit is the org.axonframework.extensions.tracing.TracingCommandGateway#sendWithSpan method.

**Comment by jvanderkallen** [comment]
> There seems to be a wrong instance of `activateSpan(parentSpan)`, following a `try (Scope ignored = tracer.activateSpan(childSpan)) { ... }`. Since the childSpan is only executed on in a Scope, there is no need to (re)activate the parent span. That is automatically done when the scope of the childSpan ended. In fact, the (re)activation of the parent span this way may cause an additional Scope to be added to the stack, which isn't properly cleared anymore.
> 
> The culprit is the org.axonframework.extensions.tracing.TracingCommandGateway#sendWithSpan method.

I believe something strange happened in [this commit](https://github.com/AxonFramework/extension-tracing/commit/bf88159b1d08cebc95b8bb7e4fbefe06b32bcc31#diff-fb88be6c3e5bebaee9671ba810cbeff8). I think I fixed this problem with pull request #17.

**Comment by lfgcampos** [comment]
@jvanderkallen you are right, as I pointed out on the PR (#32) I recently open.
Feel free to review that if you have time!

**Comment by jvanderkallen** [comment]
> @jvanderkallen you are right, as I pointed out on the PR (#32) I recently open.
> Feel free to review that if you have time!

Sorry about that, I hadn't read your pull request yet. Thanks for the clarification.

**Comment by lfgcampos** [comment]
@gerloh I've provided a PR and a fix for this issue.
Let us know if the problem is fixed on your side as well.

**Comment by gerloh** [comment]
i think this will help indeed. Although this not fixed : 
" Also i noticed that a span can be closed in another thread than it is started. This is an issue if you want you use MDC like in this Observer (as MDC is coupled to a thread):"  can start another issue for that.
